### PR TITLE
Expect revert hint

### LINKED ISSUE #26: Add a `expect_revert` hint
Similar to: https://docs.swmansion.com/protostar/docs/tutorials/testing/cheatcodes/expect-revert or https://doc.rust-lang.org/book/ch11-01-writing-tests.html#checking-for-panics-with-should_panic

It specifies that a program crash is expected and returns success when it happens

### PR DESCRIPTION
**Pull request by Bernardstanislas**
Closes #26

### CODE REVIEW

File: src/cairo_run.rs [hunk 1]
```diff
@@ -37,9 +38,16 @@ pub fn cairo_run<'a>(
...
-		.map_err(CairoRunError::VirtualMachine)?;
+	let execution_result = cairo_runner.run_until_pc(end, &mut vm, hint_processor);
+
+	match cairo_runner.exec_scopes.get_any_boxed_ref(EXPECT_REVERT_FLAG) {
+		Ok(_) if execution_result.is_ok() => Err(CairoRunError::VirtualMachine(
+			VirtualMachineError::CustomHint(EXPECT_REVERT_FLAG.to_string()),
+		))?,
+		Err(_) if execution_result.is_err() =>
+			execution_result.map_err(CairoRunError::VirtualMachine)?,
+		_ => {},
```
Comment (tdelabro) [inline src/cairo_run.rs:49]: in the case `Ok(_) if execution_result.is_err()` we do `{}`, which mean we don't handle the actual execution error coming from `cairo_runner.run_until_pc(end, &mut vm, hint_processor);`

I would do
```
	let res_execution_result = cairo_runner.run_until_pc(end, &mut vm, hint_processor);
	let revert_flag = cairo_runner.exec_scopes.get_any_boxed_ref(EXPECT_REVERT_FLAG).is_ok();
	
	match res_execution_result {
	  Ok() if revert_flag => Err(VirtualMachineError::CustomHint(EXPECT_REVERT_FLAG.to_string())),
	_ => {res_execution_result}
	}.map_err(CairoRunError::VirtualMachine)?;

**Review by tdelabro — APPROVED** [review]
